### ISSUE TITLE
Ported to .NET Core, have questions

### ISSUE THREAD

**Issue by christianhuening** [ziyasal/InfluxDB.Net#15] opened 2016-09-10 08:17 UTC
Hi there,

I tried a port to .NET Core and that worked quite well so far for the main project. The InfluxDB.NET.Posh subproject was not portable (what is Posh and what is Cmdlet?) and the tests are lacking the AutoFixture package, which seems to not be available for .NET Core yet. 

You can have a look here: https://github.com/christianhuening/InfluxDB.Net/tree/dotnetcore 
Do you have any ideas on how to proceed with that?

Cheers,
Christian

**Comment by poxet** [comment] 2016-09-16 14:12
I have not looked into the Posh project myself. Have just worked on InfluxDB.Net.sln, so I am not sure.

Perhaps we should look into having some more unit tests along with the integration tests that we have now.

I will try to have a look at your fork, but I have not worked so much with the .NET Core yet, so I am not sure that I can be of any help there.

**Comment by christianhuening** [comment] 2016-09-16 14:58
Well I think it'll work from my experience with .NET core so far (already ported some ~30 projects). I am just unsure what exactly the Posh project is.

**Comment by poxet** [comment] 2016-09-16 15:18
Perhaps the Posh solution/project is legacy and should be deprecated. If someone is opposed to that, please make comment, or I will remove that part.

**Comment by christianhuening** [comment] 2016-09-16 15:19
There is a usage of the Cmdlet-whatever. It sounds like that would be some kind of CLI ?

**Comment by cbovar** [comment] 2016-09-16 15:23
I believe 'Posh' stands for 'Powershell'. InfluxDB.NET.Posh seems to expose Influxdb to Powershell through Cmdlets.

**Comment by poxet** [comment] 2016-09-16 15:25
Sounds like a cool feature! :) I cannot get the project to build though. Perhaps should have a look at that instead then.

**Comment by ziyasal** [comment] 2016-09-16 15:35
Hi @all, sorry for joining to party late. Yep, 'Posh' stands for 'Powershell'. Someone contributed InfluxDB.NET.Posh to expose Influxdb to Powershell through Cmdlets which is cool. But we didn't spent time to improve it :( So we can create seperate project for Powershell support if you want and maybe we can implement later on.. BTW, I haven't looked at the code but porting to .Net Core seems cool 👍 

Thank you for everyone who interested!

**Comment by christianhuening** [comment] 2016-09-16 15:35
How are you trying to build it? You need the dotnet cli (https://www.microsoft.com/net/core).
If you're trying to use Visual Studio, you need Visual Studio 2015 with Update 3

**Comment by christianhuening** [comment] 2016-12-29 13:22
we'Re using my port of the influxdb lib in production. It's working quite well for us. Posh is excluded and I have my own DLL exported to our private NuGet Repo atm.

**Comment by christianhuening** [comment] 2016-12-29 13:33
@ziyasal How would you handle the dotnet core port? A branch, an additional repo?

**Comment by ziyasal** [comment] 2016-12-29 13:40
Hi @hanssens we can separate it to different repositories or we can remove 'Posh' project if there is no interest to use it (actually I am not using) @christianhuening I prefer branch way

**Comment by christianhuening** [comment] 2016-12-29 13:43
@hanssens & @ziyasal I think we then should put it into a different repo and leave it there. If anyone wants to use it, it's still available and does not hurt anybody

**Comment by ziyasal** [comment] 2016-12-29 13:46
@christianhuening  looks good to me, I will create separate repo for it.

**Comment by hanssens** [comment] 2016-12-29 13:58
Sounds like a plan. If the new repo for Posh is created by @ziyasal then maybe @christianhuening can do a PR (on a separate branch)? I'd love to look into the PR/branch as well.

**Comment by hanssens** [comment] 2016-12-29 19:23
Gents, I've taken the liberty to create a [seperate branch (dotnet-core-upgrade)](https://github.com/ziyasal/InfluxDB.Net/tree/dotnet-core-upgrade). This is a preliminary migration to dotnet core with the following in mind:

* Straight port to dotnet core (netstandard1.6)
* Leaving historic commits intact
* Backwards compatible with .NET 4.5+

However, it is not finished yet. **One issue remains** and that is the dependency on AutoFixture which is not dotnet core compatible yet. See also https://github.com/AutoFixture/AutoFixture/issues/404

Simply put, the screenshot below illustrates the issues related to AutoFixture. These prevent a build on only the Test project:

![windows_10](https://cloud.githubusercontent.com/assets/493382/21552828/954bb022-ce04-11e6-9cc6-3754ab37b7b6.png)

Now if @christianhuening's version already has a fix for this, please feel free to discard my branch entirely! Otherwise, would love some feedback and suggestions on what to do here.

Hoping you don't mind, I've also taken the opportunity to create a [Gitter channel](https://gitter.im/InfluxDB-Net/Lobby) for this. Just in case any further discussing would be required.

Would love some feedback on this...

**Comment by christianhuening** [comment] 2016-12-29 20:31
@hanssens Let me just check my version. Sorry for not being quicker.

**Comment by deandob** [comment] 2017-01-15 08:07
Guys, would really appreciate it if you could release a NUGET package for dotnet core. I'm having a hard time building the core branches mentioned here ("upgrade" and "upgrade-tests"), for the upgrade branch I can build it but I get assembly file not found when using it in my dotnet core app (and the dll sits in the project bin directory) and with the upgrade-test branch I get NUGET errors with restoring the BCL package.

Spent a bit of time already on this, so if it is no trouble please do add the working dotnet core port that is working to the nuget repository. Many thanks.

**Comment by christianhuening** [comment] 2017-01-15 10:37
@ziyasal @hanssens I take it the project uses Circle CI? Where can we see the build result?

**Comment by poxet** [comment] 2017-01-15 10:52
There is a Team City build for this project. It does not work with the .Net Core changes. I will have a look at that, so that we can have a new version pushed easily.

**Comment by christianhuening** [comment] 2017-01-15 10:55
@poxet Ok, thanks! Are you managing the TeamCity instance? Or who does it? Would make sense to share that information across the collaborators IMHO ;-)

meanwhile I'll look into the branch with the upgraded tests and see whether I can get them to run. 

What does the TeamCity build run in terms of tests etc? The build.sh? dotnet test?

**Comment by christianhuening** [comment] 2017-01-15 12:20
Ok I got AutoFixture to work by using the version from here: https://github.com/uhaciogullari/AutoFixture/tree/net-core
I added the AutoFixture subproject to the InfluxDB.NET solution for now (until an official v4 NuGet package is available for AutoFixture)

With that the original tests compile again, but fail during execution because the InfluxDB URL is not valid (http://...:8086) 
I pushed all that into a new branch:
https://github.com/ziyasal/InfluxDB.Net/tree/dotnet-core-upgrade-withAutoFixture

Does anybody know how the original tests were intended to run? Are you supposed to start up an InfluxDB instance via Docker on the CI server for instance?

**Comment by poxet** [comment] 2017-01-15 13:19
I got the impression that the test was intended to be run manually as needed. It would be better to have the integration tests run automatically on push.

As of now the Team City build is not really used fully, it might as well have been a power shell script. No tests are run there and it is triggered manually.

This is basically what it does.
1. Powershell script that sets the version number
2. "C:\Program Files\dotnet\dotnet.exe" restore project.json
3. "C:\Program Files\dotnet\dotnet.exe" build project.json
4. "C:\Program Files\dotnet\dotnet.exe" pack project.json
5. Set a release tag with version in the git repository
6. NuGet push $package -ApiKey $apiKey -Source https://www.nuget.org

**Comment by poxet** [comment] 2017-01-15 13:20
Now there is a beta version of a new nuget package pushed that you can test.
https://www.nuget.org/packages/InfluxDB.Net.Core/1.1.22-beta

**Comment by deandob** [comment] 2017-01-15 20:03
Thanks gents. Building and running now. Have a few more issues to work through but are influxdb related not this library. Much appreciated the help to get this going especially over the weekend.

**Closed** 2017-01-15 20:30 UTC
